apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
data:
    FOO: bar
---
apiVersion: v1
kind: Pod
metadata:
  name: foobar
spec:
  containers:
  - name: proxy
    image: docker.io/library/nginx:1.25.3
    envFrom:
    - configMapRef:
        name: foo
        optional: false
